### ISSUE TITLE
Bubbles=false not possible with remodal component

### ISSUE THREAD

**Issue by nickschot** [sethbrasile/ember-remodal#11]
Currently it doesn't seem possible to add something like bubbles=false (like with normal ember actions) to the er-open-button component. Workaround would probably be to programmatically open the modal and prevent bubbling from the action. Still would be a nice addition though!

**Comment by sethbrasile** [comment]
@nickschot I apologize but I'm a little naive to the idea as I've never had a need to use `bubbles=false`, could you outline a use-case where it would be useful? How would the er-open-button behave if `bubbles=false` was set?

**Comment by nickschot** [comment]
@sethbrasile my current use case is a list of link-to's which also contain a little X at the right to delete the item. In the normal case, clicking the little X would also trigger the link-to (which is it's parent). With bubbles=false, only the action bound to X would be triggered.

Last night I used the workaround I proposed above. I put an action on the X and used ember-remodal as a service, programmattically opening the modal when the action is fired.

I'm not sure if my specific use case would work with the non-service variant as I also need to pass an argument (the item in the list which needs to be deleted) to the modal, which I don't think is possible in block or normal form (you can currently pass the action as a String argument).

**Comment by sethbrasile** [comment]
@nickschot would adding closure actions solve the same problem? I ask because I've been pondering adding them before releasing 1.0.0.

**Comment by sethbrasile** [comment]
I'm also a little naive in closure action territory, haven't had much chance to use them yet :/

**Comment by sethbrasile** [comment]
Ahh I see what you mean, you need a click handler inside of a link-to that doesn't trigger the link-to.

**Comment by sethbrasile** [comment]
Something like this @nickschot? Am I understanding the gist of it?

```hbs
{{#each items as |item|}}
  {{#link-to 'somewhere' item.id}}

    {{!-- markup for list item --}}
  
    {{#ember-remodal closeButton='Yes! Delete it!' onClose='delete'}}
      {{#er-open-button}}
        {{!-- markup for little x --}}
      {{/er-open-button}}

      <p>Are you sure you want to delete?</p>
    {{/ember-remodal}}
  {{/link-to}}
{{/each}}
```

**Comment by sethbrasile** [comment]
so that the contents of `markup for list item` when clicked, go to '`somewhere` with `item.id`' but if you click the contents of `er-open-button` you don't get transitioned, instead a modal opens.

**Comment by sethbrasile** [comment]
err... I guess `onConfirm` would be better than `onClose` in that example, but you get the point :D

**Comment by nickschot** [comment]
Yes, that is exactly how I tried to use it at first! Though now that I see this again in this case a modal would be created for every item. Not sure if that's the best way to do it. In my current (service) implementation I put it outside the #each (so there exists only one modal). It would also still be necessary to pass the item somewhere to the onConfirm action.

Might be better to just stick to the service based modal. Can't think of a use case right now where a modal wouldn't be item specific and still be nested in an anchor.

**Comment by sethbrasile** [comment]
Closing this. If anyone else thinks I should look at this again, please let me know and I may reopen.
