### ISSUE TITLE
Navigating keeps old modals on demo page resulting in a resource leak.

### ISSUE THREAD

**Issue by kitsunde** [sethbrasile/ember-remodal#18]
1. Go to https://sethbrasile.github.io/ember-remodal/#/
2. Open modal
3. Go to any other page.
4. Go back.
5. Open a modal.

There's now 2 modals in the DOM. I'm not sure if this is because it's a demo page or a general thing with ember-remodal but thought I should highlight it.

**Comment by sethbrasile** [comment]
Thanks @kitsunde, I looked at this on initial development but it blew up my tests then I forgot to come back to it :D 

Got it now though! I'll get a patch released soon (at ember conf now, so very spotty wifi)
