### ISSUE TITLE
getOwner Error

### ISSUE THREAD

**Issue by jeffstagedoor** [sethbrasile/ember-remodal#26]
First: Thanks for that wonderful addon!

I installed to an ember 2.0.1 with Ember-cli 1.13.7, Jquery 1.11.3 and get that error:

ember-remodal.js:191 Uncaught TypeError: getOwner is not a function
_getConfig	@	ember-remodal.js:191
_checkForTestingEnv	@	ember-remodal.js:173

The modal still is showing though...

Any suggestions what I'm doing wrong?

**Comment by sethbrasile** [comment]
@jeffstagedoor I _think_ you're using the wrong version of ember-remodal. For full compatibility, you should be using ember-remodal v0.1.0 for versions of ember less than 2.3.

https://github.com/sethbrasile/ember-remodal#compatibility

If you're using the modals only in inline-form it will still work, but if you include a block-form modal, I believe it will break on you.

The `getOwner` error is related to checking for a config flag to disable animations during testing, so if you don't think you'll do that, and you're only using "simple-inline" modals, you might be ok.

I do suggest using v0.1.0 though.

`ember install ember-remodal@0.1.0`

**Comment by sethbrasile** [comment]
Also @jeffstagedoor you're welcome!
