### ISSUE TITLE
How to pass data into the component template?

### ISSUE THREAD

**Issue by andrewhavens** [sethbrasile/ember-remodal#27]
Great library! It's really easy to use for opening simple modals.

However, I have a scenario that I'm having a hard time trying to solve. I'm trying to find a way to create a reusable modal template, but pass in the data that I need in order to render the template for a given scenario. For example, there could be 100 buttons on a page that would open the same template, but the form fields would be different.

I know how to open the named modal using the service, but I'm not sure how to set some data for the modal to use. Can you help me understand how this could be done? Thanks!

**Comment by sethbrasile** [comment]
This question is starting to pop up quite a bit, so I'm going to add some examples to the docs/demo app :D 

I'll leave this issue open until that's done.

**Comment by andrewhavens** [comment]
Hi @sethbrasile, I started implementing what I thought was a valid solution. However, now I'm realizing that the data is being cached. What am I doing wrong?

In my main template, I have something like this:

```
{{#ember-remodal forService=true name="my-modal"}}
  Some dynamic data that needs to be refreshed every time the modal is opened:
  {{someDynamicValue}}
{{/ember-remodal}}
```

In my controller, I open the modal:

```
myActionThatTriggersOpen(value) {
  this.set('someDynamicValue', value);
  this.get('remodal').open('my-modal');
}
```

**Comment by andrewhavens** [comment]
Hmm...maybe I'm going crazy because it seems to be working now. 🔮

**Comment by sethbrasile** [comment]
:D

**Comment by zipme** [comment]
Hi Guys, 
Is there a way to pass data from a route? I am using route-action helper so that action which triggers the modal open is in the route. I know I can do something like `this.controller.set("foo", bar)`, but it seems dirty, any idea?

**Comment by sethbrasile** [comment]
@zipme if it makes sense for the data to live on the model, put it there. If you need multiple objects in the model, use `Ember.RSVP.hash`. If it doesn't make sense for it to be in the model, it should probably be in a controller.

If you need data to change in a template, your options are basically:
  1. putting the logic in a controller
  2. putting the data in the model
  3. (from a route) using `this.controller.set` or `this.controllerFor('something').set`
