### ISSUE TITLE
opening/closing modals in quick succession does not work.

### ISSUE THREAD

**Issue by esbanarango** [sethbrasile/ember-remodal#3]
This example doesn't work:
````js
this.get('remodal').open('loading', { text: 'Uploading your contacts...' });
this.get('remodal').close('loading');
````

It has to be written like this:
````js
const modal = this.get('remodal.loading');
modal.setProperties({text: 'Uploading your contacts...'});
modal.open();
modal.close();
````

**Comment by sethbrasile** [comment]
97cce1d11d52d65f06fc194d38fc5babd74df25d adds returning promises from the `open` and `close` methods. Will confirm that this fixes.

**Comment by sethbrasile** [comment]
Yep, opening and closing remodal in quick succession does fail to close. The returned promises fix this, if `open` and `close` could potentially be in quick succession, use the returned promises to make sure `close` isn't called before `open` is finished.

**Comment by sethbrasile** [comment]
Reopening as I'd like to be able to call `open` and `close` in quick succession without waiting for a promise. For instance opening a loading modal in one route, then closing it in another.

**Comment by sethbrasile** [comment]
Closed by https://github.com/sethbrasile/ember-remodal/commit/4e2907f6ae38b83ddde687107382a47f051f63a9.

It is now possible to disable remodal's animations by setting `disableAnimation` to `true`. This makes a modal open/close instantly, so that calling `close` on a modal that isn't done opening is no longer an issue.

**Comment by esbanarango** [comment]
Yeeah! I'll pay you one :beer: in Portland!!

**Comment by sethbrasile** [comment]
:+1: :smile:
