### ISSUE TITLE
Documentation - style active link in header

### ISSUE THREAD

**Issue by nucleartide** [sethbrasile/ember-remodal#32]
It'd be nice if the active link on the header were styled. 😃 

![screenshot 2016-08-30 17 42 53](https://cloud.githubusercontent.com/assets/914228/18108219/40c31138-6ed9-11e6-81d6-dd25be9028bd.png)

**Comment by sethbrasile** [comment]
![You got it, dude](http://s2.quickmeme.com/img/15/154b3c9c7d698a21c8f731cfdfdc0b6dfc139703611443309fd8369b8a33002c.jpg)
