### ISSUE TITLE
Ember-power-select not working inside an ember-remodal.

### ISSUE THREAD

**Issue by esbanarango** [sethbrasile/ember-remodal#35]

**Comment by sethbrasile** [comment]
@esbanarango could you provide a little more info? Any ember-power-select within any ember-remodal just doesn't do anything when you click it?

**Comment by esbanarango** [comment]
@sethbrasile Sorry for the missing context. I'll add it, but yeah, basically non ember-power-select config work on any ember-remodal.

**Comment by osxi** [comment]
I went ahead and created an example repo for this: https://github.com/osxi/remodal-with-power-select-demo

Everything works fine but without the `renderInPlace`, there's some z-index issues (still works, though).

I don't think this is a bug on the ember-remodal or ember-power-select sides.

**Comment by RobIsHere** [comment]
ember power select also uses ember-wormhole. There is an option to specify its id / create the wormhole container explicitly where you want in your application. This way you can specify the display order without applying a z-index.

Maybe look at https://github.com/dockyard/ember-one-way-controls
My experience with that was much easier.
