### ISSUE TITLE
A way to use standard components as modals themselves?

### ISSUE THREAD

**Issue by joshuairl** [sethbrasile/ember-remodal#37]
I want to use `ember-remodal` but it's getting hard to manage global modal properties and things.
Wanting to break them out into their own components.

Like a `modal-login` component that is global and has it's own properties and things.

Is it a matter of just extending the ember remodal class or something?

**Comment by sethbrasile** [comment]
You could wrap a block-form `ember-remodal` in a component called `modal-login` and place that component in your application template?

Take a look here for thoughts on `state`: https://sethbrasile.github.io/ember-remodal/#/state

Please let me know if I haven't addressed your concern or if you'd like more suggestions.
