### ISSUE TITLE
Opening two uniquely named modals with service?

### ISSUE THREAD

**Issue by jfrux** [sethbrasile/ember-remodal#39]
Is it possible to open a modal using the service, and then open another one, without it closing the one before it?

**Comment by sethbrasile** [comment]
Do you mean leaving two "layers" of modals opened at once? Or do you mean that opening the 2nd modal would automatically close the 1st modal?

**Comment by zion** [comment]
I have this same issue, I would like to use 2 modals at once, almost a layering effect as you suggested. 

Currently, if another instance of remodal is opened, the first one is closed immediately. Maybe the modal content is injected into the same remodal wrapper, so therefore overwritten, giving the appearance of it closing.

**Comment by sethbrasile** [comment]
Remodal isn't designed to handle more than one modal at a time, so this is not possible without removing remodal. You may be able to simulate with CSS? Closing this until someone comes up with a plan to replace remodal :D
